server:
  port: 8090

spring:
  application:
    name: msvc-student
  datasource:
    driver-class-nam: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/schoolDb
    username: root
    password:
  jpa:
    hibernate:
     ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

